# Generated by Django 6.0.6 on 2026-06-20 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='kanban_app.offerdetail'),
        ),
    ]
