# Generated by Django 6.0.6 on 2026-06-30 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
